[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10
[[main]]
  identifier = "about-us"
  name = "About Us"
  url = "#about-us"
  weight = 20
[[main]]
  identifier = "services"
  name = "Services"
  url = "#services"
  weight = 30
[[main]]
  identifier = "contact"
  name = "Contact Us"
  url = "#contact-us"
  weight = 40